#!/bin/sh

mount -o remount,rw /

DEVICE="HB-UNI-Sen-CAP-MOIST"
DEVICE_IMG=hb-uni-sen-cap-moist.png
DEVICE_THUMB=hb-uni-sen-cap-moist_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb_unisen_capmoist.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
        sed -i "/\($DEVICE\)/d" $webuiFile
fi

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

sync
mount -o remount,ro /