#!/bin/sh
# WebUI icon used from http://icons8.com 

DEVICE="HB-UNI-Sen-PRESS"
NAME=hbunisenpress
FIRMWARE_FILE1=/firmware/rftypes/hb_unisen_press.xml
FIRMWARE_FILE2=/firmware/rftypes/hb_unisen_press-sc.xml

ADDON_DIR=/usr/local/addons/${NAME}
WWW_DIR=/etc/config/addons/www/${NAME}
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
ERRFILE=/var/log/$NAME.err

case "$1" in
	""|start)
		echo 'Starting...'
		if [ ! -f ${ADDON_DIR}/installed ] || [ ! -f ${FIRMWARE_FILE1} ] || [ ! -f ${FIRMWARE_FILE2} ]; then
			cd ${ADDON_DIR}
			echo $!> $PIDFILE & ./install > $LOGFILE 2>$ERRFILE
		else
			echo "Nothing to do for $DEVICE"
		fi
	;;

	stop)
		echo "Nothing to stop..."
	;;

	uninstall)
    		cd ${ADDON_DIR}
    		echo $!> $PIDFILE & ./uninstall > $LOGFILE 2>$ERRFILE
    		cd /
    		rm -rf $ADDON_DIR
    		rm -rf $WWW_DIR
    	;;
  
	restart|reload)
  	  # Operations to stop and start (restart) the addon
  	  stop
  	  sleep 2
  	  start
    	;;

	info)
		echo "Info: <b>$DEVICE Addon</b><br>"
		echo "Info: <a href='https://github.com/jp112sdl/$DEVICE'>https://github.com/jp112sdl/$DEVICE</a>"
		echo "Version: $(cat ${ADDON_DIR}/VERSION)"
		echo "Name: $DEVICE"
		echo "Operations: uninstall"
		#echo "Config-Url: ${CONFIG_URL}"
		echo "Update: /addons/$NAME/update-check.cgi"
	;;
	
	*)
		echo "Usage: $NAME {start|stop|restart|info|uninstall}" >&2
		exit 1
    	;;

esac

exit $?
